language: node_js
node_js: '6.10'
env:
  global:
  - secure: Y4eDn5TKEA91FvOTLu+h0RYd+4Z2bv8gYt+d2m+fh+zQq23JRLIQJDpjkV4q4CQutHO3Ze/22FOzwhMK4mBTiR/1NC8ch0NNS7EAVwpH0VilMWnoToA6BdaA/dtDn4D4k0YnMqKBvW24A83m0Gt9zGEd6CTlVdm5zfw13v1F0+DvK/AEn0AdQGCNGTZ6ZB4N8wrBHnnGbG1ijIZ2XfPKSEB6qugInK5Fkc7hStfTSlF+2tvz6ZI0RqCGwIuooUJepmRXe+iYIs8Soy6iRbR5UegftmwH62XMkjpYzHX8pWKFRS3/kz4tR2lHWRo8g3UD88OkJKgMufGbD3YUiiSSBrwkZVUttOwGaifsTN0LtIb9NzJxYm0UDyZzXKR7SKY6ZDmlqxoOas+EzM0xxule142C97bL3ocfvWDIG9Zf9hPTNVW6Emzf2QcbrOQR7Lyjr+OFXvnHcjuXwTQcofWv21fkR4bDzNdsAkLOqOe2hlbmD5LunTU/62sOrPuqHY0Hq9kq48EkBPYyWRyzwrF9KLwJCci16eDzLelnDfme7Lo503/m2QALHQjNfHXr1cez8CjMe238CUHRjqwgVruaksb6FiiHj8k26c5qj4IZviddNgcMC2aTSrCQQOEXS5JT3TtsFbV/CEfP29H8qN85UNI9OpWB8KjyavxQjVTtpkE=
  - secure: o8ASGs889Te3w5tVdeT2pD0cjblu8QZk80kQoQhCfqMSnlDvka9RESaLvRfyW97k1eDb+pCMTPxPj7SjMpXJUE7UmpFYkk3TR7lSW/9E30+9jB0Bjn7teT8JQm1iTmP9v6Wh0lJtsIDHVLJgjoZE5f7ui3wpSn40gPbzuCTlIqR1YlX8AiVhh6X2CEs45i8+preYcRmEjZZnnI/UqeykSvzuUn/wOno81o0NcVYouFh0Cploo/+qs4GKvt4YKry2TOOVYAtsyfkS+ocpAg3O9bni1MC/rEFwTDtWD65w8Bc4p3LNRH3YSJX1mMbRBV0KhE1n1KdoOd6fSYzSfsirypzbBHUVN/ywzsFUNuokJyokvxrSs6CSinNLNdKdo0fLacGsFL5B15N8SQfBhiv7AWFb+CHv3KPtWVR1NnrNYHcemPlkG4EH4TnruHPHHLVkLwhJJmrcUEfqWU5zNgO3Jqa9FwY2adOYrrhBbOuqCb5jKXLahTdqOBG/wm2iLEQXCODkKdkTcmCqmNS0/iwxRZuL05N2sNa7FZqOepkFtgt/+qAOfs/z6fSjnT+lqYKLShzzCau8adM9WiCU3cIVT7EBBti1YDF6YnIvZCM5hsSjbjKrz0hxO+UaXTzCSHFjH79GvcDtjuJ3exTN9013mMRCjQvFWe/+FIc/kKZSwz8=
before_install:
- "./scripts/decrypt.sh"
- npm install -g serverless
install: npm install
script:
- npm run test && npm run coverage
after_success: if [[ $TRAVIS_BRANCH == 'master' ]]; then npm run build; serverless
  deploy; fi
