service: riskmapbot

custom:
  projectName: twitterbot

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2
  stackTags:
    area: "US"

# You can overwrite defaults by adding the following
#  stage: dev
#  region: us-east-1

# Add one function for each Lambda
functions:
  twitterDMWebhook: # Lambda that gets triggered when user starts a conversation with Facebook Messenger bot
    handler: handler.twitterDMWebhook
    environment:
      TWITTER_CONSUMER_KEY: ${file(./env.yml):twitter_consumer_key}
      TWITTER_CONSUMER_SECRET: ${file(./env.yml):twitter_consumer_key}
      TWITTER_ACCESS_TOKEN_KEY: ${file(./env.yml):twitter_access_token_key}
      TWITTER_ACCESS_TOKEN_SECRET: ${file(./env.yml):twitter_access_token_secret}
      DEFAULT_LANG: ${file(./env.yml):defaultlang}
      FRONTEND_CARD_PATH: ${file(./env.yml):frontendcardpath}
      FRONTEND_MAP_PATH: ${file(./env.yml):frontendmappath}
      SERVER_API_KEY: ${file(./env.yml):serverapikey}
      SERVER_PATH: ${file(./env.yml):serverpath}
      SERVER_PORT: ${file(./env.yml):serverport}
    events:
      - http:
          path: twitter/webhook
          method: GET # This webhook lambda is called by Facebook to verify the tokens
          integration: lambda
  twitterReply: # Lambda that gets triggered when a message is published to the SNS topic Facebook
    handler: handler.twitterReply
    environment:
      TWITTER_CONSUMER_KEY: ${file(./env.yml):twitter_consumer_key}
      TWITTER_CONSUMER_SECRET: ${file(./env.yml):twitter_consumer_secret}
      TWITTER_ACCESS_TOKEN_KEY: ${file(./env.yml):twitter_access_token_key}
      TWITTER_ACCESS_TOKEN_SECRET: ${file(./env.yml):twitter_access_token_secret}
      DEFAULT_LANG: ${file(./env.yml):defaultlang}
      FRONTEND_CARD_PATH: ${file(./env.yml):frontendcardpath}
      FRONTEND_MAP_PATH: ${file(./env.yml):frontendmappath}
      SERVER_API_KEY: ${file(./env.yml):serverapikey}
      SERVER_PATH: ${file(./env.yml):serverpath}
      SERVER_PORT: ${file(./env.yml):serverport}
    events:
      - sns: Twitter
