service: riskmapbot

custom:
  projectName: twitterbwot

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-south-1
  stackTags:
    area: "USA"

# You can overwrite defaults by adding the following
#  stage: dev
#  region: us-east-1

# Add one function for each Lambda
functions:
  twitterDMWebhook: # Lambda that gets triggered when user starts a conversation with Facebook Messenger bot
    handler: handler.twitterDMWebhook
    environment:
      FACEBOOK_VALIDATION_TOKEN: ${file(./env.yml):facebookvalidationtoken}
      FACEBOOK_PAGE_ACCESS_TOKEN: ${file(./env.yml):facebookpageaccesstoken}
      DEFAULT_LANG: ${file(./env.yml):defaultlang}
      FRONTEND_CARD_PATH: ${file(./env.yml):frontendcardpath}
      FRONTEND_MAP_PATH: ${file(./env.yml):frontendmappath}
      SERVER_API_KEY: ${file(./env.yml):serverapikey}
      SERVER_PATH: ${file(./env.yml):serverpath}
      SERVER_PORT: ${file(./env.yml):serverport}
    events:
      - http:
          path: facebook/webhook
          method: GET # This webhook lambda is called by Facebook to verify the tokens
          integration: lambda
      - http:
          path: facebook/webhook
          method: POST # On POST, this lambda talks to the cognicity server to fetch unique cardId, constructs a response and sends the card OTL to the user
          integration: lambda
  facebookReply: # Lambda that gets triggered when a message is published to the SNS topic Facebook
    handler: handler.facebookReply
    environment:
      FACEBOOK_VALIDATION_TOKEN: ${file(./env.yml):facebookvalidationtoken}
      FACEBOOK_PAGE_ACCESS_TOKEN: ${file(./env.yml):facebookpageaccesstoken}
      DEFAULT_LANG: ${file(./env.yml):defaultlang}
      FRONTEND_CARD_PATH: ${file(./env.yml):frontendcardpath}
      FRONTEND_MAP_PATH: ${file(./env.yml):frontendmappath}
      SERVER_API_KEY: ${file(./env.yml):serverapikey}
      SERVER_PATH: ${file(./env.yml):serverpath}
      SERVER_PORT: ${file(./env.yml):serverport}
    events:
      - sns: Facebook
