service: facebookAdBuyBot

custom:
  projectName: facebookAdBuyBot

provider:
  name: aws
  runtime: nodejs6.10
  stackTags:
    area: USA
  stage: ${file(./${opt:area}.env.yml):stage}
  region: ${file(./${opt:area}.env.yml):region}

# Add one function for each Lambda
functions:
  submitAdForApproval: # Lambda that gets triggered when a message is published to the SNS topic Twitter
    handler: bin/functions/index.submitAdForApproval
##    environment:
##      FACEBOOK_VALIDATION_TOKEN: ${file(./${opt:area}.env.yml):facebookvalidationtoken}
##      FACEBOOK_ADACCOUNT_ID: ${file(./${opt:area}.env.yml):facebookadaccountid}
##      FACEBOOK_PAGE_ACCESS_TOKEN: ${file(./${opt:area}.env.yml):facebookpageaccesstoken}
##      DEFAULT_LANG: ${file(./${opt:area}.env.yml):defaultlang}
    events:
      - http: 
          path: submit
          method: POST
          cors: true

  getAdCreatives: # Lambda that gets triggered when a message is published to the SNS topic Twitter
    handler: bin/functions/index.getAdCreatives
##    environment:
##      FACEBOOK_VALIDATION_TOKEN: ${file(./${opt:area}.env.yml):facebookvalidationtoken}
##      FACEBOOK_ADACCOUNT_ID: ${file(./${opt:area}.env.yml):facebookadaccountid}
##      FACEBOOK_PAGE_ACCESS_TOKEN: ${file(./${opt:area}.env.yml):facebookpageaccesstoken}
##      DEFAULT_LANG: ${file(./${opt:area}.env.yml):defaultlang}
    events:
      - http:
          path: adCreatives
          method: get
          cors: true

plugins:
  - serverless-plugin-simulate
